// Titles from the narrative design; rooms implement the rules in Campaign.js.
export const LEVEL_NAMES = [
  "La primera señal",
  "Un círculo abierto",
  "Pasos prestados",
  "La tercera luz",
  "Antes del salto",
  "Un mensaje al revés",
  "La pausa de Luma",
  "Dos medias curvas",
  "El rastro que vuelve",
  "La puerta que escucha",
  "Bienvenido a casa",
  "La ventana ciega",
  "Sombra huérfana",
  "El reloj tímido",
  "Nuestra mesa",
  "Demasiadas esquinas",
  "El cuarto repetido",
  "La escalera ausente",
  "Aquí no llovía",
  "Una casa, dos versiones",
  "La primera curva",
  "Un centro compartido",
  "Cruza conmigo",
  "Demasiado deprisa",
  "La vuelta imperfecta",
  "Cuando te esperaba",
  "La segunda mitad",
  "Un baile a oscuras",
  "El ocho torcido",
  "Todavía sabemos",
  "Bienvenido, Nox",
  "El anillo sin cierre",
  "La palabra dudosa",
  "Flores de cristal",
  "No recuerdo bien",
  "La orden perfecta",
  "Un eco nuevo",
  "Silencio subtitulado",
  "La voz que se equivoca",
  "El jardín despierta",
  "Llegaste tarde",
  "No te importó",
  "Fue por ti",
  "Un salto pequeño",
  "Déjalo aquí",
  "La balanza de dos",
  "No tienes que cargarlo",
  "Una ventaja menos",
  "El miedo tiene nombre",
  "Más ligero",
  "Una lámpara rota",
  "Antes del ruido",
  "La sombra del fragmento",
  "Caer no es romper",
  "Una voz sin cuerpo",
  "El tiempo recortado",
  "La mano imposible",
  "¿Quién estaba allí?",
  "La escena completa",
  "Tú no estabas allí",
  "Te veo",
  "Mi puerta, tu botón",
  "Dos alturas",
  "Espera mi señal",
  "Un puente prestado",
  "Ahora tú",
  "Reflejo y realidad",
  "El vidrio recuerda",
  "Casi juntos",
  "Puedo ayudarte",
  "Ya podemos irnos",
  "Siempre de acuerdo",
  "Nuestra frase favorita",
  "Una salida demasiado fácil",
  "Cambié de opinión",
  "La sorpresa",
  "Un recuerdo discutido",
  "No eres mi archivo",
  "La imperfección elegida",
  "Una libertad real",
  "La nota de casa",
  "La nota de lluvia",
  "La nota del baile",
  "La nota que falta",
  "Cuatro formas",
  "No era ese orden",
  "Entre sus órdenes",
  "Un paso libre",
  "Alargar la pausa",
  "Nos encontramos allí",
  "Precisión",
  "Momentum",
  "Cooperación",
  "El salón de los reflejos",
  "Cómo salir",
  "Lo que no ocurrió",
  "Lo que sí elegí",
  "La oferta de PRISMA",
  "El paso que es tuyo",
  "Nadie despierta solo"
];
