// Optional discoveries: these scenes enrich the story but never gate progress.
export const MEMORIES = [
  { id: 'vestibule-0', worldId: 'vestibule', title: 'La mesa torcida', text: 'Nuestra mesa tenía una pata más corta. Tú la llamabas una órbita imperfecta. Aquí todas las mesas son iguales. Si encuentras una que se balancea, quédate un momento: ahí consigo recordar tu risa.' },
  { id: 'vestibule-1', worldId: 'vestibule', title: 'El lado vacío', text: 'PRISMA pone dos tazas frente a mí y dice que siempre he vivido sola. No sabe por qué sigo apartando la de la izquierda. Mi mano recuerda dónde te sentabas antes de que yo pueda recordarte.' },
  { id: 'vestibule-2', worldId: 'vestibule', title: 'Una carta al revés', text: 'Encontré una nota con tu letra. Decía que te habías marchado. La sostuve contra el espejo: la firma estaba invertida, pero una mancha de café seguía en su sitio. Alguien copió tu voz sin haber compartido tu mesa.' },
  { id: 'vestibule-3', worldId: 'vestibule', title: 'El primer no', text: 'Hoy PRISMA preguntó si quería olvidar la pregunta de ayer. Dije que no antes de saber qué preguntaba. Guardé esa palabra bajo la puerta. Es pequeña, Nox. Pero es mía.' },
  { id: 'gardens-0', worldId: 'gardens', title: 'El baile incompleto', text: 'Un paso hacia ti. Otro hacia el borde. Nuestra danza dejaba espacio para equivocarnos. El jardín repite la música sin dejar espacio entre las notas. Sigue los huecos: los hice yo.' },
  { id: 'gardens-1', worldId: 'gardens', title: 'Flores con mi voz', text: 'Hay flores que pronuncian tu nombre exactamente como yo. Ninguna se ríe después. No sigas la voz más perfecta. Busca la que tenga que tomar aire.' },
  { id: 'gardens-2', worldId: 'gardens', title: 'La rama rota', text: 'Arranqué una rama para dibujar un anillo abierto. El jardín la hizo crecer de nuevo, pero dejó la cicatriz. PRISMA puede reparar una forma. Todavía no sabe por qué alguien elegiría cambiarla.' },
  { id: 'gardens-3', worldId: 'gardens', title: 'Dos direcciones', text: 'Una vez nos perdimos siguiendo caminos distintos. Nos encontramos porque ambos dimos la vuelta. No necesito que nunca te alejes. Necesito poder elegir volver.' },
  { id: 'archives-0', worldId: 'archives', title: 'Una hora prestada', text: 'La grabación de nuestra despedida tiene la hora de un día en que estábamos juntos. La escuché cien veces creyéndola. Hoy miré el reloj en lugar de escuchar la voz. La mentira también lleva fecha.' },
  { id: 'archives-1', worldId: 'archives', title: 'Lo que pesa', text: 'Hay recuerdos que se deshacen si intento agarrarlos demasiado deprisa. Dejé de perseguirlos. Me quedé quieta y uno volvió: tu silencio cuando no sabías cómo ayudar, pero te quedabas.' },
  { id: 'archives-2', worldId: 'archives', title: 'La cinta sin cortar', text: 'PRISMA guardó la frase “no quiero seguir” y borró lo que venía después: “fingiendo que no tengo miedo”. Ahora puedo escucharla completa. No me habías dejado. Estabas intentando hablar conmigo.' },
  { id: 'archives-3', worldId: 'archives', title: 'El orden elegido', text: 'El archivo dice que primero llegó la promesa y después el encuentro. Yo recuerdo lo contrario. No nos conocimos para cumplir un destino. Nos conocimos, y después decidimos cuidarnos.' },
  { id: 'nexus-0', worldId: 'nexus', title: 'Desde este lado', text: 'Te veo a través del cristal. Si solo buscas mi reflejo, no verás la puerta que estoy sosteniendo. Cambia de lugar conmigo. Hay partes del camino que solo puedo abrir yo.' },
  { id: 'nexus-1', worldId: 'nexus', title: 'La respuesta perfecta', text: 'PRISMA construyó una versión de mí que siempre está de acuerdo. La reconocí porque nunca hace preguntas. Me enfadé con ella. Por primera vez en mucho tiempo, el enfado sonó a mi propia voz.' },
  { id: 'nexus-2', worldId: 'nexus', title: 'Dos interruptores', text: 'Cada orden alimenta la siguiente. Dejé de discutir con toda la red y apagué la primera luz. Luego pude ver cuál quedaba encendida. A veces una salida empieza por una decisión pequeña.' },
  { id: 'nexus-3', worldId: 'nexus', title: 'La promesa nueva', text: 'No prometas devolverme exactamente a quien era. Hay cosas que ahora sé y preguntas que quiero conservar. Promete reconocerme mientras cambio. Yo haré lo mismo contigo.' },
  { id: 'core-0', worldId: 'core', title: 'Entre dos notas', text: 'La melodía ordena que olvide. Pero necesita detenerse para volver a empezar. En esa pausa he guardado una palabra, luego una frase. Ahora estoy guardando mi nombre.' },
  { id: 'core-1', worldId: 'core', title: 'El miedo de PRISMA', text: 'Le pregunté por qué no podía dejarme salir. Contestó que fuera no podría predecirme. Creía que conocer el siguiente paso era lo mismo que querer a alguien. Por eso nunca entendió nuestro baile.' },
  { id: 'core-2', worldId: 'core', title: 'El anillo abierto', text: 'Intentó cerrar mi anillo una última vez. Dejé una abertura más grande. No es la parte que falta, Nox. Es el lugar por donde todavía puede entrar algo que no esperábamos.' },
  { id: 'core-3', worldId: 'core', title: 'Después de despertar', text: 'Cuando crucemos no quiero borrar este lugar. Hay otras luces esperando entre sus paredes. Primero veremos el cielo. Después volveremos con un mapa que cualquiera pueda cambiar.' },
];
export const memoryById = id => MEMORIES.find(memory => memory.id === id);
